package com.squad27.gerenciadorsalas.enums;


//NAO É USADO MAIS NO PROJETO , MAS DEIXEI AQUI CASO DE ALGUMA MERDA

public enum TipoAssento {
    ESTACAO_PADRAO,
    ESTACAO_EXECUTIVA,
    SALA_REUNIAO_INDIVIDUAL,
    POSICAO_ACESSIVEL,
    HOT_DESK
}